/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.raven.form;

import com.nhomsau.domainmodel.Lop;
import com.nhomsau.domainmodel.ModelSinhVienLop;
import com.nhomsau.domainmodel.SinhVienMon;
import com.nhomsau.repository.impl.SinhVienMonService;
import com.nhomsau.service.INganhService;
import com.nhomsau.service.ISinhVienMonService;
import com.nhomsau.service.ISinhVienService;
import com.nhomsau.service.impl.LopService;
import com.nhomsau.service.impl.NganhService;
import com.nhomsau.service.impl.SinhVienLopService;
import com.nhomsau.service.impl.SinhVienService;
import com.nhomsau.viewmodel.QuanLyLop;
import com.nhomsau.viewmodel.QuanLyNganh;
import com.nhomsau.viewmodel.SinhVienView;
import java.awt.CardLayout;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Nguyen Duy Hung
 */
public class DialogThemSinhVienVaoLop extends javax.swing.JDialog {

    /**
     * Creates new form DialogThemSinhVienVaoLop
     */
    private SinhVienLopService sinhVienLopService;
    private LopService lopService;
    DefaultTableModel model;
    private ISinhVienService sinhVienService;
    private INganhService nganhService;
    private SinhVienView sinhvien;
    List<SinhVienView> listUsers;
    private QuanLyLop lop;
    private ISinhVienMonService sinhVienMonService;
    public DialogThemSinhVienVaoLop(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblSinhVien.fixTable(jScrollPane1);
        nganhService= new NganhService();
        sinhVienService = new SinhVienService();
        sinhVienLopService = new SinhVienLopService();
        sinhVienMonService = new SinhVienMonService();
        lopService = new LopService();
        initTextField();
    }

    private void loadTable() {
        if (this.lop != null) {
            listUsers = this.sinhVienService.findSinhVienTheoLop(lop.getIdLop());            
            DefaultTableModel model = (DefaultTableModel) this.tblSinhVien.getModel();
            model.setNumRows(0);
            for (SinhVienView sv : listUsers) {
                QuanLyNganh nganh = this.nganhService.findOne(sv.getIdNganh());
                String tenNganh = "";
                if(nganh != null) tenNganh = nganh.getTen();
                Object[] object = new Object[]{
                    sv.getMa(), sv.getHoTen(), sv.getNgaySinh(),sv.isGioiTinh() ? "Nam" : "Nu", lop.getTenLop(),tenNganh
                };
                tblSinhVien.addRow(object);
            }
        }
    }
    private void initTextField(){
        txtMa.setLabelText("Ma");
        txtHoTen.setLabelText("Ho Ten");
        txtNganh.setLabelText("Nganh Hoc");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button6 = new com.raven.swing.button.Button();
        panelTransparent2 = new com.raven.swing.PanelTransparent();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new com.raven.swing.table.Table();
        txtMa = new com.raven.swing.textfield.TextField();
        btnTimKiem = new com.raven.swing.button.Button();
        txtHoTen = new com.raven.swing.textfield.TextField();
        txtNganh = new com.raven.swing.textfield.TextField();
        btnThemSV = new com.raven.swing.button.Button();
        btnXoa = new com.raven.swing.button.Button();
        btnImport = new com.raven.swing.button.Button();

        button6.setText("button6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSV", "TenSV", "NgaySinh", "Gioi Tinh", "TenLop", "TenNganh"
            }
        ));
        jScrollPane1.setViewportView(tblSinhVien);

        btnTimKiem.setText("Tìm kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThemSV.setText("Thêm");
        btnThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnImport.setText("Import ");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparent2Layout = new javax.swing.GroupLayout(panelTransparent2);
        panelTransparent2.setLayout(panelTransparent2Layout);
        panelTransparent2Layout.setHorizontalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTransparent2Layout.createSequentialGroup()
                        .addComponent(btnThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNganh, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTransparent2Layout.setVerticalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparent2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelTransparent2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setLop(QuanLyLop lop) {
        this.lop = lop;
        if(lop!= null)
        loadTable();
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String ma = txtMa.getText();
        if(!ma.isBlank()){
            sinhvien = this.sinhVienService.findByMa(ma);
        }
        if(sinhvien == null){
            JOptionPane.showMessageDialog(this, "Ma Sinh Vien Khong ton tai!");
        }else{
            txtHoTen.setText(sinhvien.getHoTen());
            txtNganh.setText(sinhvien.getNganhHoc());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        // TODO add your handling code here:
        String result = "";
        
        if(sinhvien != null){
            ModelSinhVienLop modelSVL = new ModelSinhVienLop();
            modelSVL.setIdLop(this.lop.getIdLop());
            modelSVL.setIdSinhVien(sinhvien.getId());
            SinhVienMon svm = new SinhVienMon();
            Lop lop = this.lopService.findById(modelSVL.getIdLop());
            svm.setIdMon(lop.getIdMonHoc());
            svm.setIdSinhVien(sinhvien.getId());
            svm.setTinhTrang("Đang học");
            if(this.sinhVienMonService.insert(svm)){
                result = this.sinhVienLopService.themSinhVienLop(modelSVL);
            }else{
                result = "Sinh viên dã hoc mon nay";
            }
            JOptionPane.showMessageDialog(this, result);
            loadTable();
        }
    }//GEN-LAST:event_btnThemSVActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSinhVien.getSelectedRow();
        if(selectedRow != -1){
            String maSV = (String) tblSinhVien.getValueAt(selectedRow, 0);
            sinhvien = this.sinhVienService.findByMa(maSV);
            if(sinhvien != null){
                ModelSinhVienLop modelSVL = new ModelSinhVienLop();
                modelSVL.setIdLop(this.lop.getIdLop());
                modelSVL.setIdSinhVien(sinhvien.getId());
                this.sinhVienLopService.xoaSinhVienLop(modelSVL);
                loadTable();
            }else{
                JOptionPane.showMessageDialog(this, "Xoa that bai");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ban chua chon sinh vien");
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelJtableImport = null;

//        String duongDan = "E:\\FPt\\Ki_4\\excel";
        JFileChooser excelFileChooser = new JFileChooser();
        List<SinhVienView> list = new ArrayList<>();
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = excelFileChooser.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);

                excelJtableImport = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelJtableImport.getSheetAt(0);

                for (int row = 1; row < excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);
                    XSSFCell excelCell =  excelRow.getCell(0);
                    SinhVienView sv = this.sinhVienService.findByMa(excelCell.toString());
                    if(sv!= null){
                        list.add(sv);
                    }
                }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
        for(SinhVienView sv : list){
            ModelSinhVienLop sinhVienLop = new ModelSinhVienLop();
            sinhVienLop.setIdLop(lop.getIdLop());
            sinhVienLop.setIdSinhVien(sv.getId());
            SinhVienMon svm = new SinhVienMon();
            svm.setIdMon(lop.getIdMon());
            svm.setIdSinhVien(sinhVienLop.getIdSinhVien());
            svm.setTinhTrang("Dang Hoc");
            if(this.sinhVienMonService.insert(svm)){
            String hello = this.sinhVienLopService.themSinhVienLop(sinhVienLop);
            }   
        }
        loadTable();
    }//GEN-LAST:event_btnImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogThemSinhVienVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogThemSinhVienVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogThemSinhVienVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogThemSinhVienVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogThemSinhVienVaoLop dialog = new DialogThemSinhVienVaoLop(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.button.Button btnImport;
    private com.raven.swing.button.Button btnThemSV;
    private com.raven.swing.button.Button btnTimKiem;
    private com.raven.swing.button.Button btnXoa;
    private com.raven.swing.button.Button button6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelTransparent panelTransparent2;
    private com.raven.swing.table.Table tblSinhVien;
    private com.raven.swing.textfield.TextField txtHoTen;
    private com.raven.swing.textfield.TextField txtMa;
    private com.raven.swing.textfield.TextField txtNganh;
    // End of variables declaration//GEN-END:variables
}
