/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.nhomsau.domainmodel.BangDiem;
import com.nhomsau.viewmodel.QuanLyKy;
import com.nhomsau.viewmodel.QuanLyMon;
import com.nhomsau.repository.impl.DiemRepository;
import com.nhomsau.repository.IKyRepository;
import com.nhomsau.repository.impl.KyRepository;
import com.nhomsau.service.impl.DiemService;
import com.nhomsau.service.IDiemService;
import com.nhomsau.service.IKyService;
import com.nhomsau.service.IMonService;
import com.nhomsau.service.impl.KyService;
import com.nhomsau.service.impl.MonService;
import com.nhomsau.util.CheckLogin;
import com.nhomsau.viewmodel.BangDiemTheoMon;
import com.nhomsau.viewmodel.LoginModel;
import com.raven.dialog.Message;
import com.raven.main.MainStudent;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Hung
 */
public class FormBangDiemTheoKy extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    DefaultComboBoxModel cbx;
    IKyService iKyService;
    IMonService iMonService;
    IDiemService iDiemService;
    List<QuanLyKy> li;
    DefaultTableModel model;
    List<BangDiem> list;
    private LoginModel modelLogin;
    public FormBangDiemTheoKy() {
        initComponents();
        if(CheckLogin.isLogin()){
            modelLogin = CheckLogin.loginModel;
            model = (DefaultTableModel) tbDiem.getModel();
            iKyService = new KyService();
            iMonService = new MonService();
            iDiemService=new DiemService();
            li = new ArrayList<>();
            cbcKy.setLabeText("Ky");
            cbxMon.setLabeText("Mon");
            getAllKy();
            
        }
//        this.showMessage("Bạn cần thêm " + (10- Double.valueOf(lblDiemTrungBinh.getText())) + "để qua môn " + lblMon.getText());
  //      loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDiem = new com.raven.swing.table.Table();
        jLabel5 = new javax.swing.JLabel();
        panelTransparent2 = new com.raven.swing.PanelTransparent();
        jLabel1 = new javax.swing.JLabel();
        lblDiemTrungBinh = new javax.swing.JLabel();
        panelTransparent3 = new com.raven.swing.PanelTransparent();
        jLabel2 = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        panelTransparent1 = new com.raven.swing.PanelTransparent();
        cbxMon = new com.raven.swing.combobox.Combobox();
        cbcKy = new com.raven.swing.combobox.Combobox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMon.setForeground(new java.awt.Color(0, 0, 0));
        lblMon.setText("1: COM107");

        tbDiem.setBackground(new java.awt.Color(255, 255, 255));
        tbDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Tên đầu điểm", "Điểm", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDiem);

        jLabel5.setText("1/5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Trung Bình:");

        lblDiemTrungBinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiemTrungBinh.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelTransparent2Layout = new javax.swing.GroupLayout(panelTransparent2);
        panelTransparent2.setLayout(panelTransparent2Layout);
        panelTransparent2Layout.setHorizontalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparent2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(panelTransparent2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelTransparent2Layout.setVerticalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Trạng Thái");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelTransparent3Layout = new javax.swing.GroupLayout(panelTransparent3);
        panelTransparent3.setLayout(panelTransparent3Layout);
        panelTransparent3Layout.setHorizontalGroup(
            panelTransparent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparent3Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        panelTransparent3Layout.setVerticalGroup(
            panelTransparent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(panelTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(294, 294, 294)
                                .addComponent(panelTransparent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTransparent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTransparent1.setOpaque(true);

        cbxMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMonItemStateChanged(evt);
            }
        });
        cbxMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMonActionPerformed(evt);
            }
        });

        cbcKy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcKyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbcKy, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(cbxMon, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void getAllKy() {
        cbx = (DefaultComboBoxModel) cbcKy.getModel();
        cbx.removeAllElements();
        List<QuanLyKy> list = iKyService.findAll();
        li = iKyService.findAll();
        for (QuanLyKy k : list) {
            cbx.addElement(k);
        }
    }

   
    private void loadTable(){
        QuanLyMon mon1 = (QuanLyMon) cbxMon.getSelectedItem();
        model.setNumRows(0);
        if (mon1 != null) {
            if (modelLogin != null) {
                list = new DiemRepository().getDiem(modelLogin.getIdUser(), mon1.getId());
                for (BangDiem b : list) {
                    Object[] obj = new Object[]{
                        tbDiem.getRowCount() + 1,
                        b.getTenDauDiem(),
                        b.getDiem(),
                        b.getGhiCHu()
                    };
                    tbDiem.addRow(obj);
                }
            }
        }
    }

    private void cbxMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMonActionPerformed
       

    }//GEN-LAST:event_cbxMonActionPerformed

    private void cbxMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMonItemStateChanged
        // TODO add your handling code here:
        QuanLyMon mon1 = (QuanLyMon) cbxMon.getSelectedItem();
        QuanLyKy ky = (QuanLyKy) cbcKy.getSelectedItem();
        loadTable();
        // TODO add your handling code here:
        if(mon1!= null){
            if(modelLogin != null){
                BangDiemTheoMon bdtm = iDiemService.getDiemTrungBinhTheoId(modelLogin.getIdUser(), ky.getId(), modelLogin.getIdNganh(), mon1.getId());
                if(bdtm!= null){
                    lblDiemTrungBinh.setText(bdtm.getDiemTB() + "");
                    String trangThai = "";
                    if(bdtm.getDiemTB() >=5){
                        trangThai = "Passed";
                        lblTrangThai.setForeground(Color.GREEN);
                    }else {
                        trangThai = "Failed";
                        lblTrangThai.setForeground(Color.red);
                    }
                    lblTrangThai.setText(trangThai);
                    lblMon.setText(mon1.getTen());
                }
            }
           
            
        }
    }//GEN-LAST:event_cbxMonItemStateChanged

    private void showMessage(String value){
        Message message = new Message(MainStudent.getFrames()[0], true);
        message.showMessage(value);
    }
    private void cbcKyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcKyItemStateChanged
        // TODO add your handling code here:
        QuanLyKy k = (QuanLyKy) cbcKy.getSelectedItem();
        if (k != null) {
            System.out.println(k.getTen());
        }
        List<QuanLyMon> lists = this.iMonService.findMon(k.getId(),modelLogin.getIdNganh());
        cbxMon.removeAllItems();
        if (!lists.isEmpty()) {
            for (QuanLyMon mo : lists) {
                cbxMon.addItem(mo);
            }

        }
    }//GEN-LAST:event_cbcKyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.combobox.Combobox cbcKy;
    private com.raven.swing.combobox.Combobox cbxMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTrungBinh;
    private javax.swing.JLabel lblMon;
    private javax.swing.JLabel lblTrangThai;
    private com.raven.swing.PanelTransparent panelTransparent1;
    private com.raven.swing.PanelTransparent panelTransparent2;
    private com.raven.swing.PanelTransparent panelTransparent3;
    private com.raven.swing.table.Table tbDiem;
    // End of variables declaration//GEN-END:variables
}
