/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.nhomsau.repository.ISinhVienRepository;
import com.nhomsau.repository.impl.SinhVienRepository;
import com.nhomsau.util.CheckLogin;
import com.nhomsau.viewmodel.LoginModel;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HaTanBinh
 */
public class Form_DoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form Form_DoiMatKhau
     */
    ISinhVienRepository iSinhVienRepository;
    String checkCode ;
    private LoginModel modelLogin;
    public Form_DoiMatKhau() {
        initComponents();
        if (CheckLogin.isLogin()) {
            modelLogin = CheckLogin.loginModel;
        }
        iSinhVienRepository = new SinhVienRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new com.raven.swing.textfield.TextField();
        txtCode = new com.raven.swing.textfield.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCode = new com.raven.swing.button.Button();
        btcXacNhan = new com.raven.swing.button.Button();

        textField1.setText("textField1");

        setPreferredSize(new java.awt.Dimension(700, 375));

        jLabel1.setText("Code");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Bạn hãy nhập code đã được gửi vào email của bạn để tiếp tục.");

        btnCode.setText("Gui code");
        btnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeActionPerformed(evt);
            }
        });

        btcXacNhan.setText("xac nhan");
        btcXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(1078, 1078, 1078))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnCode, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btcXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btcXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeActionPerformed
        // TODO add your handling code here:
        try {
            Properties p = new Properties();
            p.put("mail.smtp.port", "587");
            p.put("mail.smtp.auth", true);
            p.put("mail.smtp.starttls.enable", true);
            p.put("mail.smtp.host", "smtp.gmail.com");

            Session s = Session.getDefaultInstance(p,
                    new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication("binhhtph27077@fpt.edu.vn", "tanbinh17092003");
                }
            });
            Message m = new MimeMessage(s);
            String subject = "test đổi mật khẩu";
            String to = modelLogin.getIdUser();
            double randomDouble = Math.random();
            randomDouble = randomDouble * 999999 + 1;
            int randomInt = (int) randomDouble;
            checkCode=String.valueOf(randomInt);
            String tieuDe = "test";
            String message = "code để thay đỏi mật khẩu là :" + randomInt;
            m.setFrom(new InternetAddress("binhhtph27077@fpt.edu.vn"));
            m.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            m.setSubject(tieuDe);
            m.setText(message);
            Transport.send(m);
            //JOptionPane.showMessageDialog(this, "Send Email SuccessFully!");
        } catch (MessagingException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCodeActionPerformed
    
    private void btcXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcXacNhanActionPerformed
        // TODO add your handling code here:
        
         String code=txtCode.getText();
        if(code.equalsIgnoreCase(checkCode)){
           new DialogDoiMatKhau(new JFrame(), true).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "sai code hoac ban chua gui code");
            return;
        }
    }//GEN-LAST:event_btcXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.button.Button btcXacNhan;
    private com.raven.swing.button.Button btnCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.raven.swing.textfield.TextField textField1;
    private com.raven.swing.textfield.TextField txtCode;
    // End of variables declaration//GEN-END:variables
}
