/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.nhomsau.service.IDauDiemService;
import com.nhomsau.service.impl.DauDiemService;
import com.nhomsau.util.Validatetor;
import com.nhomsau.viewmodel.QuanLyDauDiem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Hung
 */
public class FormDauDiem extends javax.swing.JPanel {

    /**
     * Creates new form FormDauDiem
     */
    private final IDauDiemService dauDiemService;
    public FormDauDiem() {
        initComponents();
        dauDiemService = new DauDiemService();
        loadTable();
    }
    private void loadTable(){
        DefaultTableModel model = (DefaultTableModel) tblDauDiem.getModel();
        model.setNumRows(0);
        List<QuanLyDauDiem> listDauDiems = this.dauDiemService.findAllView();
        for(QuanLyDauDiem dd : listDauDiems){
            Object[] objects = new Object[]{
                dd.getMa(),dd.getTen()
            };
            tblDauDiem.addRow(objects);
        }
    }
    private QuanLyDauDiem validateDauDiem(){
        String ma = Validatetor.kiemTraRong(txtMa, "Ma khong duoc trong");
        if(ma == null) return null;
        String ten = Validatetor.kiemTraRong(txtTen, "Ten khong duoc trong");
        if(ten == null) return null;
        QuanLyDauDiem dauDiem = new QuanLyDauDiem(ma, ten);
        return dauDiem;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransparent1 = new com.raven.swing.PanelTransparent();
        txtMa = new com.raven.swing.textfield.TextField();
        txtTen = new com.raven.swing.textfield.TextField();
        btnThem = new com.raven.swing.button.Button();
        btnSua = new com.raven.swing.button.Button();
        btnXoa = new com.raven.swing.button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDauDiem = new com.raven.swing.table.Table();

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblDauDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ma", "Ten Dau Dien"
            }
        ));
        tblDauDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDauDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDauDiem);

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        QuanLyDauDiem dauDiem = this.validateDauDiem();
        if(dauDiem != null){
           int confirm = JOptionPane.showConfirmDialog(this, "Ban co muon them khong?");
           if(confirm == JOptionPane.YES_OPTION){
               this.dauDiemService.insert(dauDiem);
               loadTable();
           }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDauDiem.getSelectedRow();
        if(selectedRow != -1){
            QuanLyDauDiem dauDiem = this.validateDauDiem();
            if(dauDiem != null){
               int confirm = JOptionPane.showConfirmDialog(this, "Ban co muon sua khong?");
               if(confirm == JOptionPane.YES_OPTION){
                   this.dauDiemService.update(dauDiem);
                   loadTable();
               }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDauDiem.getSelectedRow();
        if(selectedRow != -1){
            String ma = (String) tblDauDiem.getValueAt(selectedRow, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Ban co muon xoa khong?");
               if(confirm == JOptionPane.YES_OPTION){
                   this.dauDiemService.delete(ma);
                   loadTable();
               }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDauDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDauDiemMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblDauDiem.getSelectedRow();
        String ma = (String) tblDauDiem.getValueAt(selectedRow, 0);
        String ten = (String) tblDauDiem.getValueAt(selectedRow, 1);
        txtMa.setText(ma);
        txtTen.setText(ten);
    }//GEN-LAST:event_tblDauDiemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.button.Button btnSua;
    private com.raven.swing.button.Button btnThem;
    private com.raven.swing.button.Button btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelTransparent panelTransparent1;
    private com.raven.swing.table.Table tblDauDiem;
    private com.raven.swing.textfield.TextField txtMa;
    private com.raven.swing.textfield.TextField txtTen;
    // End of variables declaration//GEN-END:variables
}
