/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.microsoft.schemas.office.excel.STObjectType;
import com.nhomsau.domainmodel.Lop;
import com.nhomsau.mapper.GiangVienMapper;
import com.nhomsau.service.IManageLecturerService;
import com.nhomsau.service.IMonService;
import com.nhomsau.service.ISinhVienService;
import com.nhomsau.service.impl.LopService;
import com.nhomsau.service.impl.ManageLecturerService;
import com.nhomsau.service.impl.MonService;
import com.nhomsau.service.impl.SinhVienService;
import com.nhomsau.viewmodel.ManageLecturer;
import com.nhomsau.viewmodel.QuanLyGiangVien;
import com.nhomsau.viewmodel.QuanLyLop;
import com.nhomsau.viewmodel.QuanLyMon;
import com.raven.main.Main;
import java.awt.Point;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Hung
 */
public class LopHocPanel extends javax.swing.JPanel {

    /**
     * Creates new form LopHocPanel
     */
    private LopService lopService;
    private IMonService monService;
    private ISinhVienService sinhVienService;
    private IManageLecturerService lecturerService;
    DefaultTableModel model;
    List<QuanLyLop> list;
    public LopHocPanel() {
        initComponents();
        initTextField();
        lecturerService = new ManageLecturerService();
        sinhVienService = new SinhVienService();
        tblLop.setComponentPopupMenu(pmMenu);
        model = (DefaultTableModel) tblLop.getModel();
        lopService = new LopService();
        monService = new MonService();
        list = lopService.findAll();
        loadTable();
        initComBoBox();
        
    }
    private void initTextField(){
        txtID.setLabelText("Id");
        txtID.setEditable(false);
        txtMa.setLabelText("Ma Lop");
        txtTen.setLabelText("Ten Lop");
        txtTimKiem.setLabelText("Tim Kiem");
        cbxGiangVien.setLabeText("Giang Vien");
        cbxMon.setLabeText("Mon");
        
        
    }
    private void initComBoBox(){
        List<QuanLyMon> listMon = monService.findAll();
        if(!listMon.isEmpty()){
            for(QuanLyMon mon: listMon){
                cbxMon.addItem(mon);
            }
        }
        List<QuanLyGiangVien> manageLecturers = lecturerService.getAll();
        if(!manageLecturers.isEmpty()){
            for(QuanLyGiangVien lecturer : manageLecturers){
                cbxGiangVien.addItem(lecturer);
            }
        }
    }
    private void loadTable(){
        model.setNumRows(0);
        list = this.lopService.findAll();
        for(QuanLyLop lop : list){
            QuanLyMon mon = monService.findOne(lop.getIdMon());
            System.out.println(lop.getIdMon());
            QuanLyGiangVien manager = this.lecturerService.findById(lop.getIdGiaoVien());
            Object[] obj = new Object[]{
                lop.getMaLop(),lop.getTenLop(),mon,manager.getHoTen()
            };
            tblLop.addRow(obj);
        }
    }
    private Lop validateLop(){
        String ma = txtMa.getText();
        String ten = txtTen.getText();      
        QuanLyMon mon = (QuanLyMon) cbxMon.getSelectedItem();
        QuanLyGiangVien manageLecturer = (QuanLyGiangVien) cbxGiangVien.getSelectedItem();
        Lop lop = new Lop();
        lop.setIdMonHoc(mon.getId());
        lop.setMaLop(ma);
        lop.setTenLop(ten);
        lop.setIdGiaoVien(manageLecturer.getId());
        return lop;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmMenu = new javax.swing.JPopupMenu();
        DanhSach = new javax.swing.JMenuItem();
        ThemSinhVien = new javax.swing.JMenuItem();
        panelTransparent1 = new com.raven.swing.PanelTransparent();
        txtID = new com.raven.swing.textfield.TextField();
        txtMa = new com.raven.swing.textfield.TextField();
        txtTen = new com.raven.swing.textfield.TextField();
        btnThem = new com.raven.swing.button.Button();
        btnSua = new com.raven.swing.button.Button();
        cbxMon = new com.raven.swing.combobox.Combobox();
        cbxGiangVien = new com.raven.swing.combobox.Combobox();
        panelTransparent2 = new com.raven.swing.PanelTransparent();
        txtTimKiem = new com.raven.swing.textfield.TextField();
        btnTimKiem = new com.raven.swing.button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLop = new com.raven.swing.table.Table();
        button3 = new com.raven.swing.button.Button();

        pmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmMenuMouseClicked(evt);
            }
        });

        DanhSach.setText("jMenuItem1");
        DanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachMouseClicked(evt);
            }
        });
        pmMenu.add(DanhSach);

        ThemSinhVien.setText("jMenuItem2");
        pmMenu.add(ThemSinhVien);

        panelTransparent1.setOpaque(true);

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxMon, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(cbxGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelTransparent2.setOpaque(true);

        btnTimKiem.setText("Tìm Kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblLop.setBackground(new java.awt.Color(255, 255, 255));
        tblLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Lop", "Ten Lop", "Mon", "GiangVien"
            }
        ));
        tblLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLop);

        button3.setText("Thêm Sinh Viên");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparent2Layout = new javax.swing.GroupLayout(panelTransparent2);
        panelTransparent2.setLayout(panelTransparent2Layout);
        panelTransparent2Layout.setHorizontalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        panelTransparent2Layout.setVerticalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTransparent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMaActionPerformed

    private void tblLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLopMouseClicked
        // TODO add your handling code here:
        if(SwingUtilities.isLeftMouseButton(evt)){
        int row = tblLop.getSelectedRow();
        if (row < 0) {
            return;
        }
        String ma = model.getValueAt(row, 0).toString();
        String ten = model.getValueAt(row, 1).toString();
        txtMa.setText(ma);
        txtTen.setText(ten);
        }else {
            Point p = evt.getPoint();
            int row = tblLop.rowAtPoint(p);
            tblLop.setRowSelectionInterval(row, row);
            
        }
    }//GEN-LAST:event_tblLopMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your  code here:
        Lop lop = this.validateLop();
        this.lopService.insert(lop);
        loadTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maLop = txtTimKiem.getText();
        if(!maLop.isBlank()){
            list = this.lopService.findByTen(maLop);
        }else{
            list = this.lopService.findAll();
        }
        loadTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(tblLop.getSelectedRow() != -1){
        Lop lop = this.validateLop();
        
        this.lopService.update(lop);
        loadTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void pmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmMenuMouseClicked
        // TODO add your handling code here:
        JPopupMenu menu = (JPopupMenu) evt.getSource();
        DialogThemSinhVienVaoLop dialog = new DialogThemSinhVienVaoLop(Main.getFrames()[0], true);
        System.out.println(menu.getComponent(0).getName());
        if(menu.getComponent(0).getName().equalsIgnoreCase("Danhsach")){
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_pmMenuMouseClicked

    private void DanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogThemSinhVienVaoLop dialog = new DialogThemSinhVienVaoLop(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_DanhSachMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblLop.getSelectedRow();
        if(selectedRow != -1){
            String maLop = (String) model.getValueAt(selectedRow, 0);
            QuanLyLop lop = this.lopService.findByMa(maLop);
           if(lop != null) 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogThemSinhVienVaoLop dialog = new DialogThemSinhVienVaoLop(new javax.swing.JFrame(), true);
                dialog.setLop(lop);
                dialog.setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_button3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DanhSach;
    private javax.swing.JMenuItem ThemSinhVien;
    private com.raven.swing.button.Button btnSua;
    private com.raven.swing.button.Button btnThem;
    private com.raven.swing.button.Button btnTimKiem;
    private com.raven.swing.button.Button button3;
    private com.raven.swing.combobox.Combobox cbxGiangVien;
    private com.raven.swing.combobox.Combobox cbxMon;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelTransparent panelTransparent1;
    private com.raven.swing.PanelTransparent panelTransparent2;
    private javax.swing.JPopupMenu pmMenu;
    private com.raven.swing.table.Table tblLop;
    private com.raven.swing.textfield.TextField txtID;
    private com.raven.swing.textfield.TextField txtMa;
    private com.raven.swing.textfield.TextField txtTen;
    private com.raven.swing.textfield.TextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
